# Generated by Django 6.1.1 on 2026-09-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hunt',
            fields=[
                ('hunt_Id', models.AutoField(primary_key=True, serialize=False)),
                ('hunt_Name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
